# Generated by Django 4.1 on 2023-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_amount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
