# Generated by Django 4.1 on 2023-04-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_cart_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="total_amount", new_name="totalAmount",
        ),
        migrations.RemoveField(model_name="order", name="price",),
        migrations.RemoveField(model_name="order", name="product",),
        migrations.RemoveField(model_name="order", name="quantity",),
    ]
