# Generated by Django 4.1 on 2023-04-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_total_amount_cart_totalamount_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="totalAmount",),
    ]
