# Generated by Django 4.1 on 2023-04-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_cartitem_person"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartitem", name="person",),
        migrations.RemoveField(model_name="order", name="payment",),
        migrations.RemoveField(model_name="transaction", name="order",),
        migrations.AddField(
            model_name="order",
            name="transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.transaction",
            ),
            preserve_default=False,
        ),
    ]
