# Generated by Django 4.1 on 2023-04-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_cartitem_person_remove_order_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.transaction",
            ),
        ),
    ]
